### ISSUE TITLE
Pubkey-only login

### ISSUE THREAD

**Issue by staab** [staab/coracle#15]
Suggested [here](http://localhost:5173/alerts#modal=eyJub3RlIjp7ImlkIjoiYjY3ODZmOTk3NjgyOWJjMjgxM2Q3ZjA2M2I3YjVjNzdjNzEwMTUyN2NiMjU3MmU4NGQ5M2NjMjU0NDUxZDUwZiIsInB1YmtleSI6IjdjYzMyOGEwOGRkYjJhZmRmOWY5YmU3N2JlZmY0YzgzNDg5ZmY5Nzk3MjE4MjdkNjI4YTU0MmYzMmEyNDdjMGUiLCJjcmVhdGVkX2F0IjoxNjcxOTAzNzA4LCJraW5kIjoxLCJ0YWdzIjpbWyJwIiwiOTdjNzBhNDQzNjZhNjUzNWMxNDViMzMzZjk3M2VhODZkZmRjMmQ3YTk5ZGE2MThjNDBjNjQ3MDVhZDk4ZTMyMiJdXSwiY29udGVudCI6IiNbMF0gY2FuIHdlIGdldCBhIHB1YiBrZXkgbG9naW4gZm9yIHJlYWQgb25seSBsb2dpbiBmb3IgY29yYWNsZS5zb2NpYWw/ICB0aGVuIGkgY291bGQgdXNlIGl0IGZyb20gbXkgYW5kcm9pZCBwaG9uZSBqdXN0IHRvIHNlZSBzdHVmZi4uIiwic2lnIjoiNjEwODNlZDMwOGExNGQzZWNlOTcyZDgxNDc1MDcxY2Q3YmNjNGU4YjcwMTViZDBlZjc5NzQ2ZGVhOTdmZTI2NTM2ZDA4ZGM3MDBhYTAzNmQzMDBmNjJkZmU4ZjQ3MDhlNTRkM2JlMTRkMjg3OTIzMGI2Njg1OWQ2NzJkN2E4OTkiLCJsb2FkZWRfYXQiOjE2NzE5MTUwMDAsInJlYWN0aW9ucyI6W10sImh0bWwiOiJAPGEgaHJlZj1cIi9wZW9wbGUvOTdjNzBhNDQzNjZhNjUzNWMxNDViMzMzZjk3M2VhODZkZmRjMmQ3YTk5ZGE2MThjNDBjNjQ3MDVhZDk4ZTMyMi9ub3Rlc1wiIGNsYXNzPVwidW5kZXJsaW5lXCI+aG9kbGJvZDwvYT4gY2FuIHdlIGdldCBhIHB1YiBrZXkgbG9naW4gZm9yIHJlYWQgb25seSBsb2dpbiBmb3IgY29yYWNsZS5zb2NpYWw/ICB0aGVuIGkgY291bGQgdXNlIGl0IGZyb20gbXkgYW5kcm9pZCBwaG9uZSBqdXN0IHRvIHNlZSBzdHVmZi4uIiwicGFyZW50IjpudWxsLCJyZXBsaWVzQ291bnQiOjAsInJlcGxpZXMiOltdfX0=)

**Comment by schlunsen** [comment]
Just want to give a shout out and say that I really like what you are doing here with coracle! 

Looking forward to follow the process

**Comment by staab** [comment]
This is done.
