### ISSUE TITLE
NIP-05 verification support

### ISSUE THREAD

**Issue by yomajo** [staab/coracle#19]
It isn't available in coracle yet, right?

**Comment by staab** [comment]
It is in fact, are you verified and not seeing a checkmark on your profile page? If so post your pubkey and I'll take a look.

**Comment by yomajo** [comment]
`npub15l8fm0fl462an4w24qh7u5a4v6cj0d8gcsvaxk0tyuyxdrtxem3sn70ar3`

Actually I can't find edit profile section for that matter. My username for which I have json is "Generalist" and have verification setup on other clients.
![image](https://user-images.githubusercontent.com/45366313/216767085-aa475247-a996-43b0-8ba4-39614dabdee3.png)

**Comment by staab** [comment]
Looks like this is a bug in the current version of nostr-tools, which doesn't handle capital letters in the name part of the nip05 value. I'll upgrade when master is released, and in the meantime you can change you nip05 to "generalist@"

**Comment by yomajo** [comment]
Cool ;) Will wait for update, as mentioned I have verification tied to other clients already.

**Comment by yomajo** [comment]
@staab if you don't mind, please edit your comment referring to particular username.

**Comment by staab** [comment]
Sure, this should be fixed in the next release, thanks for the bug report.
