### ISSUE TITLE
Attempted to start subscription 0389-(1,7,authors[51],since) with zero relays

### ISSUE THREAD

**Issue by jilv220** [staab/coracle#28]
Nothing loads for me.

**Comment by jilv220** [comment]
I don't know what happened, but the issue resolved after I reconnect one of my relays. Still confused on what's causing the issue.

**Comment by staab** [comment]
This is a known issue, it relies on Coracle being able to load your relay selections from the network, which isn't 100% reliable. It'll improve over time.
