### ISSUE TITLE
Flagged notes showing up in liked tab in profile

### ISSUE THREAD

**Issue by nwfistere** [staab/coracle#29]
Flagged notes showing up own in likes tab in profile

To reproduce:
1. Flag a note as offensive
2. Go to your own profile
3. switch to the "likes" tab
4. See flagged note with the "You have flagged this content as offensive." Although you can see the original comment initially.

**Comment by staab** [comment]
That's a pretty annoying bug, isn't it? Fixed in 0570ad60ad68a10ca4706fc23af6e680823af50d
