### ISSUE TITLE
On Firefox, Coracle loads the main page but no buttons are functional, and console is showing a CORS error

### ISSUE THREAD

**Issue by ghobs91** [staab/coracle#30]
Error message:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sessions.bugsnag.com/. (Reason: CORS request did not succeed). Status code: (null).`

**Comment by staab** [comment]
The CORS error shouldn't break anything, what OS, and are you in private mode?

**Comment by igmaat** [comment]
Reproducible in Firefox `110.0.11`, but _only_ in private browsing mode, which limits access to some local storage features, at least IndexDB. Thus the error:

`InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`

Followed by some subsequent unhandled promise rejections, which causes the "no buttons are functional".

Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

**Comment by ghobs91** [comment]
> The CORS error shouldn't break anything, what OS, and are you in private mode?

OS: MacOS Ventura 13.2 Beta
Browser: Firefox 111.0b3 (64-bit)

**Not** in a private tab/window, and I tried turning off tracking protection, disabling privacy badger and ublock origin, no dice, still that same error.

**Comment by ghobs91** [comment]
Appears fixed now!
