### ISSUE TITLE
Weirdly-formatted HTML in the middle of the note

### ISSUE THREAD

**Issue by fiatjaf** [staab/coracle#39]
See the second paragraph:

![2023-03-07-200133_939x611_scrot](https://user-images.githubusercontent.com/1653275/223574249-24079eef-fd38-4a70-b487-41ba84bb6ec3.png)

**Comment by staab** [comment]
I've seen this, it's the fault of clients who put html into notes. What do you think is the right approach?

**Comment by staab** [comment]
35a9274
